# Generated by Django 4.1.5 on 2023-01-17 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_student_image_alter_student_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
